services:
  bot_ollama:
    image: ollama/ollama
    container_name: bot_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./init_ollama.sh:/init_ollama.sh
    entrypoint: ["/bin/bash", "/init_ollama.sh"]

  bot_python:
    build: .
    env_file: .env
    container_name: bot_python
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - bot_ollama
    environment:
      - OLLAMA_HOST=http://bot_ollama:11434

volumes:
  ollama_models:
